// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: huawei_api_message.proto

#ifndef PROTOBUF_huawei_5fapi_5fmessage_2eproto__INCLUDED
#define PROTOBUF_huawei_5fapi_5fmessage_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3002000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3002000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace huawei {
namespace api {
class ApplyQosRequest;
class ApplyQosRequestDefaultTypeInternal;
extern ApplyQosRequestDefaultTypeInternal _ApplyQosRequest_default_instance_;
class ApplyQosResponse;
class ApplyQosResponseDefaultTypeInternal;
extern ApplyQosResponseDefaultTypeInternal _ApplyQosResponse_default_instance_;
class HeartbeatRequest;
class HeartbeatRequestDefaultTypeInternal;
extern HeartbeatRequestDefaultTypeInternal _HeartbeatRequest_default_instance_;
class HeartbeatResponse;
class HeartbeatResponseDefaultTypeInternal;
extern HeartbeatResponseDefaultTypeInternal _HeartbeatResponse_default_instance_;
class HuaweiApiMessage;
class HuaweiApiMessageDefaultTypeInternal;
extern HuaweiApiMessageDefaultTypeInternal _HuaweiApiMessage_default_instance_;
class RemoveQosRequest;
class RemoveQosRequestDefaultTypeInternal;
extern RemoveQosRequestDefaultTypeInternal _RemoveQosRequest_default_instance_;
class RemoveQosResponse;
class RemoveQosResponseDefaultTypeInternal;
extern RemoveQosResponseDefaultTypeInternal _RemoveQosResponse_default_instance_;
}  // namespace api
}  // namespace huawei

namespace huawei {
namespace api {

namespace protobuf_huawei_5fapi_5fmessage_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_huawei_5fapi_5fmessage_2eproto

enum ErrorCode {
  ERROR_CODE_NONE = 0,
  ERROR_CODE_UNKNOWN = 1,
  ERROR_CODE_INVALID_MSG = 2,
  ERROR_CODE_APPLY_QOS_FAILED = 3,
  ERROR_CODE_REMOVE_QOS_FAILED = 4,
  ErrorCode_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  ErrorCode_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool ErrorCode_IsValid(int value);
const ErrorCode ErrorCode_MIN = ERROR_CODE_NONE;
const ErrorCode ErrorCode_MAX = ERROR_CODE_REMOVE_QOS_FAILED;
const int ErrorCode_ARRAYSIZE = ErrorCode_MAX + 1;

const ::google::protobuf::EnumDescriptor* ErrorCode_descriptor();
inline const ::std::string& ErrorCode_Name(ErrorCode value) {
  return ::google::protobuf::internal::NameOfEnum(
    ErrorCode_descriptor(), value);
}
inline bool ErrorCode_Parse(
    const ::std::string& name, ErrorCode* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ErrorCode>(
    ErrorCode_descriptor(), name, value);
}
// ===================================================================

class HuaweiApiMessage : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:huawei.api.HuaweiApiMessage) */ {
 public:
  HuaweiApiMessage();
  virtual ~HuaweiApiMessage();

  HuaweiApiMessage(const HuaweiApiMessage& from);

  inline HuaweiApiMessage& operator=(const HuaweiApiMessage& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const HuaweiApiMessage& default_instance();

  enum MessageTypeCase {
    kApplyQosRequest = 1,
    kApplyQosResponse = 2,
    kRemoveQosRequest = 3,
    kRemoveQosResponse = 4,
    kHeartbeatRequest = 5,
    kHeartbeatResponse = 6,
    MESSAGE_TYPE_NOT_SET = 0,
  };

  static inline const HuaweiApiMessage* internal_default_instance() {
    return reinterpret_cast<const HuaweiApiMessage*>(
               &_HuaweiApiMessage_default_instance_);
  }

  void Swap(HuaweiApiMessage* other);

  // implements Message ----------------------------------------------

  inline HuaweiApiMessage* New() const PROTOBUF_FINAL { return New(NULL); }

  HuaweiApiMessage* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const HuaweiApiMessage& from);
  void MergeFrom(const HuaweiApiMessage& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(HuaweiApiMessage* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .huawei.api.ApplyQosRequest apply_qos_request = 1;
  bool has_apply_qos_request() const;
  void clear_apply_qos_request();
  static const int kApplyQosRequestFieldNumber = 1;
  const ::huawei::api::ApplyQosRequest& apply_qos_request() const;
  ::huawei::api::ApplyQosRequest* mutable_apply_qos_request();
  ::huawei::api::ApplyQosRequest* release_apply_qos_request();
  void set_allocated_apply_qos_request(::huawei::api::ApplyQosRequest* apply_qos_request);

  // .huawei.api.ApplyQosResponse apply_qos_response = 2;
  bool has_apply_qos_response() const;
  void clear_apply_qos_response();
  static const int kApplyQosResponseFieldNumber = 2;
  const ::huawei::api::ApplyQosResponse& apply_qos_response() const;
  ::huawei::api::ApplyQosResponse* mutable_apply_qos_response();
  ::huawei::api::ApplyQosResponse* release_apply_qos_response();
  void set_allocated_apply_qos_response(::huawei::api::ApplyQosResponse* apply_qos_response);

  // .huawei.api.RemoveQosRequest remove_qos_request = 3;
  bool has_remove_qos_request() const;
  void clear_remove_qos_request();
  static const int kRemoveQosRequestFieldNumber = 3;
  const ::huawei::api::RemoveQosRequest& remove_qos_request() const;
  ::huawei::api::RemoveQosRequest* mutable_remove_qos_request();
  ::huawei::api::RemoveQosRequest* release_remove_qos_request();
  void set_allocated_remove_qos_request(::huawei::api::RemoveQosRequest* remove_qos_request);

  // .huawei.api.RemoveQosResponse remove_qos_response = 4;
  bool has_remove_qos_response() const;
  void clear_remove_qos_response();
  static const int kRemoveQosResponseFieldNumber = 4;
  const ::huawei::api::RemoveQosResponse& remove_qos_response() const;
  ::huawei::api::RemoveQosResponse* mutable_remove_qos_response();
  ::huawei::api::RemoveQosResponse* release_remove_qos_response();
  void set_allocated_remove_qos_response(::huawei::api::RemoveQosResponse* remove_qos_response);

  // .huawei.api.HeartbeatRequest heartbeat_request = 5;
  bool has_heartbeat_request() const;
  void clear_heartbeat_request();
  static const int kHeartbeatRequestFieldNumber = 5;
  const ::huawei::api::HeartbeatRequest& heartbeat_request() const;
  ::huawei::api::HeartbeatRequest* mutable_heartbeat_request();
  ::huawei::api::HeartbeatRequest* release_heartbeat_request();
  void set_allocated_heartbeat_request(::huawei::api::HeartbeatRequest* heartbeat_request);

  // .huawei.api.HeartbeatResponse heartbeat_response = 6;
  bool has_heartbeat_response() const;
  void clear_heartbeat_response();
  static const int kHeartbeatResponseFieldNumber = 6;
  const ::huawei::api::HeartbeatResponse& heartbeat_response() const;
  ::huawei::api::HeartbeatResponse* mutable_heartbeat_response();
  ::huawei::api::HeartbeatResponse* release_heartbeat_response();
  void set_allocated_heartbeat_response(::huawei::api::HeartbeatResponse* heartbeat_response);

  MessageTypeCase message_type_case() const;
  // @@protoc_insertion_point(class_scope:huawei.api.HuaweiApiMessage)
 private:
  void set_has_apply_qos_request();
  void set_has_apply_qos_response();
  void set_has_remove_qos_request();
  void set_has_remove_qos_response();
  void set_has_heartbeat_request();
  void set_has_heartbeat_response();

  inline bool has_message_type() const;
  void clear_message_type();
  inline void clear_has_message_type();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  union MessageTypeUnion {
    MessageTypeUnion() {}
    ::huawei::api::ApplyQosRequest* apply_qos_request_;
    ::huawei::api::ApplyQosResponse* apply_qos_response_;
    ::huawei::api::RemoveQosRequest* remove_qos_request_;
    ::huawei::api::RemoveQosResponse* remove_qos_response_;
    ::huawei::api::HeartbeatRequest* heartbeat_request_;
    ::huawei::api::HeartbeatResponse* heartbeat_response_;
  } message_type_;
  mutable int _cached_size_;
  ::google::protobuf::uint32 _oneof_case_[1];

  friend struct  protobuf_huawei_5fapi_5fmessage_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ApplyQosRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:huawei.api.ApplyQosRequest) */ {
 public:
  ApplyQosRequest();
  virtual ~ApplyQosRequest();

  ApplyQosRequest(const ApplyQosRequest& from);

  inline ApplyQosRequest& operator=(const ApplyQosRequest& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ApplyQosRequest& default_instance();

  static inline const ApplyQosRequest* internal_default_instance() {
    return reinterpret_cast<const ApplyQosRequest*>(
               &_ApplyQosRequest_default_instance_);
  }

  void Swap(ApplyQosRequest* other);

  // implements Message ----------------------------------------------

  inline ApplyQosRequest* New() const PROTOBUF_FINAL { return New(NULL); }

  ApplyQosRequest* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ApplyQosRequest& from);
  void MergeFrom(const ApplyQosRequest& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ApplyQosRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string local_ip = 1;
  void clear_local_ip();
  static const int kLocalIpFieldNumber = 1;
  const ::std::string& local_ip() const;
  void set_local_ip(const ::std::string& value);
  #if LANG_CXX11
  void set_local_ip(::std::string&& value);
  #endif
  void set_local_ip(const char* value);
  void set_local_ip(const char* value, size_t size);
  ::std::string* mutable_local_ip();
  ::std::string* release_local_ip();
  void set_allocated_local_ip(::std::string* local_ip);

  // @@protoc_insertion_point(class_scope:huawei.api.ApplyQosRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr local_ip_;
  mutable int _cached_size_;
  friend struct  protobuf_huawei_5fapi_5fmessage_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ApplyQosResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:huawei.api.ApplyQosResponse) */ {
 public:
  ApplyQosResponse();
  virtual ~ApplyQosResponse();

  ApplyQosResponse(const ApplyQosResponse& from);

  inline ApplyQosResponse& operator=(const ApplyQosResponse& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ApplyQosResponse& default_instance();

  static inline const ApplyQosResponse* internal_default_instance() {
    return reinterpret_cast<const ApplyQosResponse*>(
               &_ApplyQosResponse_default_instance_);
  }

  void Swap(ApplyQosResponse* other);

  // implements Message ----------------------------------------------

  inline ApplyQosResponse* New() const PROTOBUF_FINAL { return New(NULL); }

  ApplyQosResponse* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ApplyQosResponse& from);
  void MergeFrom(const ApplyQosResponse& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ApplyQosResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string reason = 2;
  void clear_reason();
  static const int kReasonFieldNumber = 2;
  const ::std::string& reason() const;
  void set_reason(const ::std::string& value);
  #if LANG_CXX11
  void set_reason(::std::string&& value);
  #endif
  void set_reason(const char* value);
  void set_reason(const char* value, size_t size);
  ::std::string* mutable_reason();
  ::std::string* release_reason();
  void set_allocated_reason(::std::string* reason);

  // .huawei.api.ErrorCode error_code = 1;
  void clear_error_code();
  static const int kErrorCodeFieldNumber = 1;
  ::huawei::api::ErrorCode error_code() const;
  void set_error_code(::huawei::api::ErrorCode value);

  // @@protoc_insertion_point(class_scope:huawei.api.ApplyQosResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr reason_;
  int error_code_;
  mutable int _cached_size_;
  friend struct  protobuf_huawei_5fapi_5fmessage_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class RemoveQosRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:huawei.api.RemoveQosRequest) */ {
 public:
  RemoveQosRequest();
  virtual ~RemoveQosRequest();

  RemoveQosRequest(const RemoveQosRequest& from);

  inline RemoveQosRequest& operator=(const RemoveQosRequest& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RemoveQosRequest& default_instance();

  static inline const RemoveQosRequest* internal_default_instance() {
    return reinterpret_cast<const RemoveQosRequest*>(
               &_RemoveQosRequest_default_instance_);
  }

  void Swap(RemoveQosRequest* other);

  // implements Message ----------------------------------------------

  inline RemoveQosRequest* New() const PROTOBUF_FINAL { return New(NULL); }

  RemoveQosRequest* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const RemoveQosRequest& from);
  void MergeFrom(const RemoveQosRequest& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(RemoveQosRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:huawei.api.RemoveQosRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  mutable int _cached_size_;
  friend struct  protobuf_huawei_5fapi_5fmessage_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class RemoveQosResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:huawei.api.RemoveQosResponse) */ {
 public:
  RemoveQosResponse();
  virtual ~RemoveQosResponse();

  RemoveQosResponse(const RemoveQosResponse& from);

  inline RemoveQosResponse& operator=(const RemoveQosResponse& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RemoveQosResponse& default_instance();

  static inline const RemoveQosResponse* internal_default_instance() {
    return reinterpret_cast<const RemoveQosResponse*>(
               &_RemoveQosResponse_default_instance_);
  }

  void Swap(RemoveQosResponse* other);

  // implements Message ----------------------------------------------

  inline RemoveQosResponse* New() const PROTOBUF_FINAL { return New(NULL); }

  RemoveQosResponse* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const RemoveQosResponse& from);
  void MergeFrom(const RemoveQosResponse& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(RemoveQosResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string reason = 2;
  void clear_reason();
  static const int kReasonFieldNumber = 2;
  const ::std::string& reason() const;
  void set_reason(const ::std::string& value);
  #if LANG_CXX11
  void set_reason(::std::string&& value);
  #endif
  void set_reason(const char* value);
  void set_reason(const char* value, size_t size);
  ::std::string* mutable_reason();
  ::std::string* release_reason();
  void set_allocated_reason(::std::string* reason);

  // .huawei.api.ErrorCode error_code = 1;
  void clear_error_code();
  static const int kErrorCodeFieldNumber = 1;
  ::huawei::api::ErrorCode error_code() const;
  void set_error_code(::huawei::api::ErrorCode value);

  // @@protoc_insertion_point(class_scope:huawei.api.RemoveQosResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr reason_;
  int error_code_;
  mutable int _cached_size_;
  friend struct  protobuf_huawei_5fapi_5fmessage_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class HeartbeatRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:huawei.api.HeartbeatRequest) */ {
 public:
  HeartbeatRequest();
  virtual ~HeartbeatRequest();

  HeartbeatRequest(const HeartbeatRequest& from);

  inline HeartbeatRequest& operator=(const HeartbeatRequest& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const HeartbeatRequest& default_instance();

  static inline const HeartbeatRequest* internal_default_instance() {
    return reinterpret_cast<const HeartbeatRequest*>(
               &_HeartbeatRequest_default_instance_);
  }

  void Swap(HeartbeatRequest* other);

  // implements Message ----------------------------------------------

  inline HeartbeatRequest* New() const PROTOBUF_FINAL { return New(NULL); }

  HeartbeatRequest* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const HeartbeatRequest& from);
  void MergeFrom(const HeartbeatRequest& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(HeartbeatRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:huawei.api.HeartbeatRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  mutable int _cached_size_;
  friend struct  protobuf_huawei_5fapi_5fmessage_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class HeartbeatResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:huawei.api.HeartbeatResponse) */ {
 public:
  HeartbeatResponse();
  virtual ~HeartbeatResponse();

  HeartbeatResponse(const HeartbeatResponse& from);

  inline HeartbeatResponse& operator=(const HeartbeatResponse& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const HeartbeatResponse& default_instance();

  static inline const HeartbeatResponse* internal_default_instance() {
    return reinterpret_cast<const HeartbeatResponse*>(
               &_HeartbeatResponse_default_instance_);
  }

  void Swap(HeartbeatResponse* other);

  // implements Message ----------------------------------------------

  inline HeartbeatResponse* New() const PROTOBUF_FINAL { return New(NULL); }

  HeartbeatResponse* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const HeartbeatResponse& from);
  void MergeFrom(const HeartbeatResponse& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(HeartbeatResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:huawei.api.HeartbeatResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  mutable int _cached_size_;
  friend struct  protobuf_huawei_5fapi_5fmessage_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// HuaweiApiMessage

// .huawei.api.ApplyQosRequest apply_qos_request = 1;
inline bool HuaweiApiMessage::has_apply_qos_request() const {
  return message_type_case() == kApplyQosRequest;
}
inline void HuaweiApiMessage::set_has_apply_qos_request() {
  _oneof_case_[0] = kApplyQosRequest;
}
inline void HuaweiApiMessage::clear_apply_qos_request() {
  if (has_apply_qos_request()) {
    delete message_type_.apply_qos_request_;
    clear_has_message_type();
  }
}
inline  const ::huawei::api::ApplyQosRequest& HuaweiApiMessage::apply_qos_request() const {
  // @@protoc_insertion_point(field_get:huawei.api.HuaweiApiMessage.apply_qos_request)
  return has_apply_qos_request()
      ? *message_type_.apply_qos_request_
      : ::huawei::api::ApplyQosRequest::default_instance();
}
inline ::huawei::api::ApplyQosRequest* HuaweiApiMessage::mutable_apply_qos_request() {
  if (!has_apply_qos_request()) {
    clear_message_type();
    set_has_apply_qos_request();
    message_type_.apply_qos_request_ = new ::huawei::api::ApplyQosRequest;
  }
  // @@protoc_insertion_point(field_mutable:huawei.api.HuaweiApiMessage.apply_qos_request)
  return message_type_.apply_qos_request_;
}
inline ::huawei::api::ApplyQosRequest* HuaweiApiMessage::release_apply_qos_request() {
  // @@protoc_insertion_point(field_release:huawei.api.HuaweiApiMessage.apply_qos_request)
  if (has_apply_qos_request()) {
    clear_has_message_type();
    ::huawei::api::ApplyQosRequest* temp = message_type_.apply_qos_request_;
    message_type_.apply_qos_request_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline void HuaweiApiMessage::set_allocated_apply_qos_request(::huawei::api::ApplyQosRequest* apply_qos_request) {
  clear_message_type();
  if (apply_qos_request) {
    set_has_apply_qos_request();
    message_type_.apply_qos_request_ = apply_qos_request;
  }
  // @@protoc_insertion_point(field_set_allocated:huawei.api.HuaweiApiMessage.apply_qos_request)
}

// .huawei.api.ApplyQosResponse apply_qos_response = 2;
inline bool HuaweiApiMessage::has_apply_qos_response() const {
  return message_type_case() == kApplyQosResponse;
}
inline void HuaweiApiMessage::set_has_apply_qos_response() {
  _oneof_case_[0] = kApplyQosResponse;
}
inline void HuaweiApiMessage::clear_apply_qos_response() {
  if (has_apply_qos_response()) {
    delete message_type_.apply_qos_response_;
    clear_has_message_type();
  }
}
inline  const ::huawei::api::ApplyQosResponse& HuaweiApiMessage::apply_qos_response() const {
  // @@protoc_insertion_point(field_get:huawei.api.HuaweiApiMessage.apply_qos_response)
  return has_apply_qos_response()
      ? *message_type_.apply_qos_response_
      : ::huawei::api::ApplyQosResponse::default_instance();
}
inline ::huawei::api::ApplyQosResponse* HuaweiApiMessage::mutable_apply_qos_response() {
  if (!has_apply_qos_response()) {
    clear_message_type();
    set_has_apply_qos_response();
    message_type_.apply_qos_response_ = new ::huawei::api::ApplyQosResponse;
  }
  // @@protoc_insertion_point(field_mutable:huawei.api.HuaweiApiMessage.apply_qos_response)
  return message_type_.apply_qos_response_;
}
inline ::huawei::api::ApplyQosResponse* HuaweiApiMessage::release_apply_qos_response() {
  // @@protoc_insertion_point(field_release:huawei.api.HuaweiApiMessage.apply_qos_response)
  if (has_apply_qos_response()) {
    clear_has_message_type();
    ::huawei::api::ApplyQosResponse* temp = message_type_.apply_qos_response_;
    message_type_.apply_qos_response_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline void HuaweiApiMessage::set_allocated_apply_qos_response(::huawei::api::ApplyQosResponse* apply_qos_response) {
  clear_message_type();
  if (apply_qos_response) {
    set_has_apply_qos_response();
    message_type_.apply_qos_response_ = apply_qos_response;
  }
  // @@protoc_insertion_point(field_set_allocated:huawei.api.HuaweiApiMessage.apply_qos_response)
}

// .huawei.api.RemoveQosRequest remove_qos_request = 3;
inline bool HuaweiApiMessage::has_remove_qos_request() const {
  return message_type_case() == kRemoveQosRequest;
}
inline void HuaweiApiMessage::set_has_remove_qos_request() {
  _oneof_case_[0] = kRemoveQosRequest;
}
inline void HuaweiApiMessage::clear_remove_qos_request() {
  if (has_remove_qos_request()) {
    delete message_type_.remove_qos_request_;
    clear_has_message_type();
  }
}
inline  const ::huawei::api::RemoveQosRequest& HuaweiApiMessage::remove_qos_request() const {
  // @@protoc_insertion_point(field_get:huawei.api.HuaweiApiMessage.remove_qos_request)
  return has_remove_qos_request()
      ? *message_type_.remove_qos_request_
      : ::huawei::api::RemoveQosRequest::default_instance();
}
inline ::huawei::api::RemoveQosRequest* HuaweiApiMessage::mutable_remove_qos_request() {
  if (!has_remove_qos_request()) {
    clear_message_type();
    set_has_remove_qos_request();
    message_type_.remove_qos_request_ = new ::huawei::api::RemoveQosRequest;
  }
  // @@protoc_insertion_point(field_mutable:huawei.api.HuaweiApiMessage.remove_qos_request)
  return message_type_.remove_qos_request_;
}
inline ::huawei::api::RemoveQosRequest* HuaweiApiMessage::release_remove_qos_request() {
  // @@protoc_insertion_point(field_release:huawei.api.HuaweiApiMessage.remove_qos_request)
  if (has_remove_qos_request()) {
    clear_has_message_type();
    ::huawei::api::RemoveQosRequest* temp = message_type_.remove_qos_request_;
    message_type_.remove_qos_request_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline void HuaweiApiMessage::set_allocated_remove_qos_request(::huawei::api::RemoveQosRequest* remove_qos_request) {
  clear_message_type();
  if (remove_qos_request) {
    set_has_remove_qos_request();
    message_type_.remove_qos_request_ = remove_qos_request;
  }
  // @@protoc_insertion_point(field_set_allocated:huawei.api.HuaweiApiMessage.remove_qos_request)
}

// .huawei.api.RemoveQosResponse remove_qos_response = 4;
inline bool HuaweiApiMessage::has_remove_qos_response() const {
  return message_type_case() == kRemoveQosResponse;
}
inline void HuaweiApiMessage::set_has_remove_qos_response() {
  _oneof_case_[0] = kRemoveQosResponse;
}
inline void HuaweiApiMessage::clear_remove_qos_response() {
  if (has_remove_qos_response()) {
    delete message_type_.remove_qos_response_;
    clear_has_message_type();
  }
}
inline  const ::huawei::api::RemoveQosResponse& HuaweiApiMessage::remove_qos_response() const {
  // @@protoc_insertion_point(field_get:huawei.api.HuaweiApiMessage.remove_qos_response)
  return has_remove_qos_response()
      ? *message_type_.remove_qos_response_
      : ::huawei::api::RemoveQosResponse::default_instance();
}
inline ::huawei::api::RemoveQosResponse* HuaweiApiMessage::mutable_remove_qos_response() {
  if (!has_remove_qos_response()) {
    clear_message_type();
    set_has_remove_qos_response();
    message_type_.remove_qos_response_ = new ::huawei::api::RemoveQosResponse;
  }
  // @@protoc_insertion_point(field_mutable:huawei.api.HuaweiApiMessage.remove_qos_response)
  return message_type_.remove_qos_response_;
}
inline ::huawei::api::RemoveQosResponse* HuaweiApiMessage::release_remove_qos_response() {
  // @@protoc_insertion_point(field_release:huawei.api.HuaweiApiMessage.remove_qos_response)
  if (has_remove_qos_response()) {
    clear_has_message_type();
    ::huawei::api::RemoveQosResponse* temp = message_type_.remove_qos_response_;
    message_type_.remove_qos_response_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline void HuaweiApiMessage::set_allocated_remove_qos_response(::huawei::api::RemoveQosResponse* remove_qos_response) {
  clear_message_type();
  if (remove_qos_response) {
    set_has_remove_qos_response();
    message_type_.remove_qos_response_ = remove_qos_response;
  }
  // @@protoc_insertion_point(field_set_allocated:huawei.api.HuaweiApiMessage.remove_qos_response)
}

// .huawei.api.HeartbeatRequest heartbeat_request = 5;
inline bool HuaweiApiMessage::has_heartbeat_request() const {
  return message_type_case() == kHeartbeatRequest;
}
inline void HuaweiApiMessage::set_has_heartbeat_request() {
  _oneof_case_[0] = kHeartbeatRequest;
}
inline void HuaweiApiMessage::clear_heartbeat_request() {
  if (has_heartbeat_request()) {
    delete message_type_.heartbeat_request_;
    clear_has_message_type();
  }
}
inline  const ::huawei::api::HeartbeatRequest& HuaweiApiMessage::heartbeat_request() const {
  // @@protoc_insertion_point(field_get:huawei.api.HuaweiApiMessage.heartbeat_request)
  return has_heartbeat_request()
      ? *message_type_.heartbeat_request_
      : ::huawei::api::HeartbeatRequest::default_instance();
}
inline ::huawei::api::HeartbeatRequest* HuaweiApiMessage::mutable_heartbeat_request() {
  if (!has_heartbeat_request()) {
    clear_message_type();
    set_has_heartbeat_request();
    message_type_.heartbeat_request_ = new ::huawei::api::HeartbeatRequest;
  }
  // @@protoc_insertion_point(field_mutable:huawei.api.HuaweiApiMessage.heartbeat_request)
  return message_type_.heartbeat_request_;
}
inline ::huawei::api::HeartbeatRequest* HuaweiApiMessage::release_heartbeat_request() {
  // @@protoc_insertion_point(field_release:huawei.api.HuaweiApiMessage.heartbeat_request)
  if (has_heartbeat_request()) {
    clear_has_message_type();
    ::huawei::api::HeartbeatRequest* temp = message_type_.heartbeat_request_;
    message_type_.heartbeat_request_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline void HuaweiApiMessage::set_allocated_heartbeat_request(::huawei::api::HeartbeatRequest* heartbeat_request) {
  clear_message_type();
  if (heartbeat_request) {
    set_has_heartbeat_request();
    message_type_.heartbeat_request_ = heartbeat_request;
  }
  // @@protoc_insertion_point(field_set_allocated:huawei.api.HuaweiApiMessage.heartbeat_request)
}

// .huawei.api.HeartbeatResponse heartbeat_response = 6;
inline bool HuaweiApiMessage::has_heartbeat_response() const {
  return message_type_case() == kHeartbeatResponse;
}
inline void HuaweiApiMessage::set_has_heartbeat_response() {
  _oneof_case_[0] = kHeartbeatResponse;
}
inline void HuaweiApiMessage::clear_heartbeat_response() {
  if (has_heartbeat_response()) {
    delete message_type_.heartbeat_response_;
    clear_has_message_type();
  }
}
inline  const ::huawei::api::HeartbeatResponse& HuaweiApiMessage::heartbeat_response() const {
  // @@protoc_insertion_point(field_get:huawei.api.HuaweiApiMessage.heartbeat_response)
  return has_heartbeat_response()
      ? *message_type_.heartbeat_response_
      : ::huawei::api::HeartbeatResponse::default_instance();
}
inline ::huawei::api::HeartbeatResponse* HuaweiApiMessage::mutable_heartbeat_response() {
  if (!has_heartbeat_response()) {
    clear_message_type();
    set_has_heartbeat_response();
    message_type_.heartbeat_response_ = new ::huawei::api::HeartbeatResponse;
  }
  // @@protoc_insertion_point(field_mutable:huawei.api.HuaweiApiMessage.heartbeat_response)
  return message_type_.heartbeat_response_;
}
inline ::huawei::api::HeartbeatResponse* HuaweiApiMessage::release_heartbeat_response() {
  // @@protoc_insertion_point(field_release:huawei.api.HuaweiApiMessage.heartbeat_response)
  if (has_heartbeat_response()) {
    clear_has_message_type();
    ::huawei::api::HeartbeatResponse* temp = message_type_.heartbeat_response_;
    message_type_.heartbeat_response_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline void HuaweiApiMessage::set_allocated_heartbeat_response(::huawei::api::HeartbeatResponse* heartbeat_response) {
  clear_message_type();
  if (heartbeat_response) {
    set_has_heartbeat_response();
    message_type_.heartbeat_response_ = heartbeat_response;
  }
  // @@protoc_insertion_point(field_set_allocated:huawei.api.HuaweiApiMessage.heartbeat_response)
}

inline bool HuaweiApiMessage::has_message_type() const {
  return message_type_case() != MESSAGE_TYPE_NOT_SET;
}
inline void HuaweiApiMessage::clear_has_message_type() {
  _oneof_case_[0] = MESSAGE_TYPE_NOT_SET;
}
inline HuaweiApiMessage::MessageTypeCase HuaweiApiMessage::message_type_case() const {
  return HuaweiApiMessage::MessageTypeCase(_oneof_case_[0]);
}
// -------------------------------------------------------------------

// ApplyQosRequest

// string local_ip = 1;
inline void ApplyQosRequest::clear_local_ip() {
  local_ip_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ApplyQosRequest::local_ip() const {
  // @@protoc_insertion_point(field_get:huawei.api.ApplyQosRequest.local_ip)
  return local_ip_.GetNoArena();
}
inline void ApplyQosRequest::set_local_ip(const ::std::string& value) {
  
  local_ip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:huawei.api.ApplyQosRequest.local_ip)
}
#if LANG_CXX11
inline void ApplyQosRequest::set_local_ip(::std::string&& value) {
  
  local_ip_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:huawei.api.ApplyQosRequest.local_ip)
}
#endif
inline void ApplyQosRequest::set_local_ip(const char* value) {
  
  local_ip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:huawei.api.ApplyQosRequest.local_ip)
}
inline void ApplyQosRequest::set_local_ip(const char* value, size_t size) {
  
  local_ip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:huawei.api.ApplyQosRequest.local_ip)
}
inline ::std::string* ApplyQosRequest::mutable_local_ip() {
  
  // @@protoc_insertion_point(field_mutable:huawei.api.ApplyQosRequest.local_ip)
  return local_ip_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ApplyQosRequest::release_local_ip() {
  // @@protoc_insertion_point(field_release:huawei.api.ApplyQosRequest.local_ip)
  
  return local_ip_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ApplyQosRequest::set_allocated_local_ip(::std::string* local_ip) {
  if (local_ip != NULL) {
    
  } else {
    
  }
  local_ip_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), local_ip);
  // @@protoc_insertion_point(field_set_allocated:huawei.api.ApplyQosRequest.local_ip)
}

// -------------------------------------------------------------------

// ApplyQosResponse

// .huawei.api.ErrorCode error_code = 1;
inline void ApplyQosResponse::clear_error_code() {
  error_code_ = 0;
}
inline ::huawei::api::ErrorCode ApplyQosResponse::error_code() const {
  // @@protoc_insertion_point(field_get:huawei.api.ApplyQosResponse.error_code)
  return static_cast< ::huawei::api::ErrorCode >(error_code_);
}
inline void ApplyQosResponse::set_error_code(::huawei::api::ErrorCode value) {
  
  error_code_ = value;
  // @@protoc_insertion_point(field_set:huawei.api.ApplyQosResponse.error_code)
}

// string reason = 2;
inline void ApplyQosResponse::clear_reason() {
  reason_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ApplyQosResponse::reason() const {
  // @@protoc_insertion_point(field_get:huawei.api.ApplyQosResponse.reason)
  return reason_.GetNoArena();
}
inline void ApplyQosResponse::set_reason(const ::std::string& value) {
  
  reason_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:huawei.api.ApplyQosResponse.reason)
}
#if LANG_CXX11
inline void ApplyQosResponse::set_reason(::std::string&& value) {
  
  reason_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:huawei.api.ApplyQosResponse.reason)
}
#endif
inline void ApplyQosResponse::set_reason(const char* value) {
  
  reason_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:huawei.api.ApplyQosResponse.reason)
}
inline void ApplyQosResponse::set_reason(const char* value, size_t size) {
  
  reason_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:huawei.api.ApplyQosResponse.reason)
}
inline ::std::string* ApplyQosResponse::mutable_reason() {
  
  // @@protoc_insertion_point(field_mutable:huawei.api.ApplyQosResponse.reason)
  return reason_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ApplyQosResponse::release_reason() {
  // @@protoc_insertion_point(field_release:huawei.api.ApplyQosResponse.reason)
  
  return reason_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ApplyQosResponse::set_allocated_reason(::std::string* reason) {
  if (reason != NULL) {
    
  } else {
    
  }
  reason_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), reason);
  // @@protoc_insertion_point(field_set_allocated:huawei.api.ApplyQosResponse.reason)
}

// -------------------------------------------------------------------

// RemoveQosRequest

// -------------------------------------------------------------------

// RemoveQosResponse

// .huawei.api.ErrorCode error_code = 1;
inline void RemoveQosResponse::clear_error_code() {
  error_code_ = 0;
}
inline ::huawei::api::ErrorCode RemoveQosResponse::error_code() const {
  // @@protoc_insertion_point(field_get:huawei.api.RemoveQosResponse.error_code)
  return static_cast< ::huawei::api::ErrorCode >(error_code_);
}
inline void RemoveQosResponse::set_error_code(::huawei::api::ErrorCode value) {
  
  error_code_ = value;
  // @@protoc_insertion_point(field_set:huawei.api.RemoveQosResponse.error_code)
}

// string reason = 2;
inline void RemoveQosResponse::clear_reason() {
  reason_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& RemoveQosResponse::reason() const {
  // @@protoc_insertion_point(field_get:huawei.api.RemoveQosResponse.reason)
  return reason_.GetNoArena();
}
inline void RemoveQosResponse::set_reason(const ::std::string& value) {
  
  reason_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:huawei.api.RemoveQosResponse.reason)
}
#if LANG_CXX11
inline void RemoveQosResponse::set_reason(::std::string&& value) {
  
  reason_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:huawei.api.RemoveQosResponse.reason)
}
#endif
inline void RemoveQosResponse::set_reason(const char* value) {
  
  reason_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:huawei.api.RemoveQosResponse.reason)
}
inline void RemoveQosResponse::set_reason(const char* value, size_t size) {
  
  reason_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:huawei.api.RemoveQosResponse.reason)
}
inline ::std::string* RemoveQosResponse::mutable_reason() {
  
  // @@protoc_insertion_point(field_mutable:huawei.api.RemoveQosResponse.reason)
  return reason_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* RemoveQosResponse::release_reason() {
  // @@protoc_insertion_point(field_release:huawei.api.RemoveQosResponse.reason)
  
  return reason_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void RemoveQosResponse::set_allocated_reason(::std::string* reason) {
  if (reason != NULL) {
    
  } else {
    
  }
  reason_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), reason);
  // @@protoc_insertion_point(field_set_allocated:huawei.api.RemoveQosResponse.reason)
}

// -------------------------------------------------------------------

// HeartbeatRequest

// -------------------------------------------------------------------

// HeartbeatResponse

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace api
}  // namespace huawei

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::huawei::api::ErrorCode> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::huawei::api::ErrorCode>() {
  return ::huawei::api::ErrorCode_descriptor();
}

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_huawei_5fapi_5fmessage_2eproto__INCLUDED
